name: 'Checks'

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true
  NODE_OPTIONS: '--no-warnings'
  ASTRO_TELEMETRY_DISABLED: true

jobs:
  checks:
    name: 'Checks'
    runs-on: ['ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Get pnpm Version'
        id: pnpm-version
        run: |
          PNPM_VERSION=$(cat package.json | jq --raw-output '.packageManager' | awk -F'@' '{print $2}')
          echo "PNPM_VERSION=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.PNPM_VERSION }}


      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 'lts/*'

      - name: 'Install Dependencies'
        run: pnpm install

      - name: 'Format'
        run: pnpm dlx @biomejs/biome format . --reporter=github

      - name: 'Lint'
        run: pnpm dlx @biomejs/biome lint . --reporter=github

      - name: 'Type Check'
        run: pnpm typecheck

      - name: 'Check Dependencies'
        run: pnpm dlx sherif@latest
